name: Bazelisk
on:
  pull_request: {}
  push: {}

jobs:
  bazelisk_jobs:
    strategy:
      matrix:
        version: ["6.0.0", "6.4.0"]
    runs-on: ubuntu-latest
    name: Bazelisk
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - run: USE_BAZEL_VERSION=${{ matrix.version }} bazel test //...
