name: Bazelisk
on:
  pull_request: {}
  push: {}

jobs:
  bazelisk_jobs:
    runs-on: ubuntu-latest
    name: Bazelisk
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - run: USE_BAZEL_VERSION=6.0.0 bazel test //...
    - run: USE_BAZEL_VERSION=6.4.0 bazel test //...
